miprimerproyecto/miprimerproyecto/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'miprimerproyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^preguntas/$', 'preguntasyrespuestas.views.index', name='preguntas'),
    url(r'^preguntas/(?P<pregunta_id>\d+)/$', 'preguntasyrespuestas.views.pregunta_detalle', name='pregunta_detalle'),
)

miprimerproyecto/preguntasyrespuestas/models.py
from django.db import models
from django.utils import timezone

class Pregunta(models.Model):
	asunto = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_publicacion = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.asunto

	def publicado_hoy(self):
		return self.fecha_publicacion.date() == timezone.now().date()
	publicado_hoy.boolean = True
	publicado_hoy.short_description = 'Preguntado hoy?'


class Respuesta(models.Model):
	Pregunta = models.ForeignKey(Pregunta)
	contenido = models.TextField()
	mejor_respuesta = models.BooleanField("Respuesta preferida", default=False)

	def __def__(self):
		return self.contenido

miprimerproyecto/preguntasyrespuestas/views.py
from django.http import HttpResponse, Http404
from preguntasyrespuestas.models import Pregunta
from django.shortcuts import get_object_or_404, render_to_response

def index(request):
	preguntas = Pregunta.objects.all()
	return render_to_response('preguntasyrespuestas/index.html', {'preguntas': preguntas})

def pregunta_detalle(request, pregunta_id):
	try:
		pregunta = Pregunta.objects.get(pk=pregunta_id)
	except Pregunta.DoesNotExist:
		raise Http404

	#pregunta = get_object_or_404(Pregunta, pk=pregunta_id)

	return render_to_response('preguntasyrespuestas/pregunta_detalle.html', {'pregunta': pregunta})

miprimerproyecto/templates/preguntasyrespuestas/index.html
<html>
<body>
	{% for pregunta in preguntas %}
		<a href="{% url "pregunta_detalle" pregunta.id %}">{{ pregunta.asunto }} ?</a><br />
	{% endfor %}
</body>
</html>

miprimerproyecto/templates/preguntasyrespuestas/pregunta_detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Pregunta detalle</title>
</head>
<body>
	<h2>{{pregunta.asunto}} ?</h2>
	<p><b>Publicado: </b> {{pregunta.fecha_publicacion|date:"D, d/m/Y" }}</p>
	<p>
		{% if pregunta.descripcion %}
				{{pregunta.descripcion}}
		{% else %}
				No se ha incluido descripcion
		{% endif %}
	</p>
	<h3>Respuestas</h3>
	<ul>
		{% for respuesta in pregunta.respuesta_set.all %}
				<li>{{respuesta.contenido|safe}}</li>
		{% empty %}
			<li>Aun no hay respuestas</li>
		{% endfor %}
	</ul>
</body>
</html>